
/*
REQUIREMENTS:
    https://envasetechnologies-my.sharepoint.com/:x:/p/aaron_bryden/EWPGV93XGK1DqAQ5Tq4SKXcB-ZIFNI3ADQaHYpn7OC6T_w?rtime=Smih-RAF2Ug
*/

/*
 t_fieldmaps default ->
    t_tms_providers ->
      t_ocrvariants ->
        t_companies ->
          t_company_ocrvariant

... lowest layer takes priority.
*/


/*
set collation_connection = utf8mb4_unicode_ci;

set @VARIANT_NAME = 'WilliamGrant-import';
set @COMPANY_NAME = 'Zariz';
set @TMSPROVIDER_NAME = 'Profit Tools';

set @COMPANY_ID = (select id from t_companies where name = @COMPANY_NAME);
set @TMSPROVIDER_ID = (select id from t_tms_providers where name = @TMSPROVIDER_NAME);

set @OCRVARIANT_ID = (select id from t_ocrvariants where abbyy_variant_name = @VARIANT_NAME);
set @COMPANY_OCRVARIANT_ID = (select id from t_company_ocrvariant where t_ocrvariant_id = @OCRVARIANT_ID and t_company_id = @COMPANY_ID);
set @DEFAULT_FIELDMAP_ID = (select id from t_fieldmaps as f where f.system_default and f.replaced_at is null order by f.id desc limit 1);

select json_pretty(json_merge_patch(
     coalesce(( select f.fieldmap_config from t_fieldmaps as f                                                          where f.id = @DEFAULT_FIELDMAP_ID   ), '{}')
    ,coalesce(( select f.fieldmap_config from t_fieldmaps as f join t_tms_providers      as t on t.t_fieldmap_id = f.id where t.id = @TMSPROVIDER_ID        ), '{}')
    ,coalesce(( select f.fieldmap_config from t_fieldmaps as f join t_ocrvariants        as c on c.t_fieldmap_id = f.id where c.id = @OCRVARIANT_ID         ), '{}')
    ,coalesce(( select f.fieldmap_config from t_fieldmaps as f join t_companies          as c on c.t_fieldmap_id = f.id where c.id = @COMPANY_ID            ), '{}')
    ,coalesce(( select f.fieldmap_config from t_fieldmaps as f join t_company_ocrvariant as v on v.t_fieldmap_id = f.id where v.id = @COMPANY_OCRVARIANT_ID ), '{}')
))
\G

*/

/*
    Cushing's example "custom/refs" mapping:

    refs_custom_mapping: {
        "custom3": {"value": "No"},
        "custom8": {"source": "actual_destination"},
        "ds_equip_req": {"source": "ship_comment"},
        "ds_ref2_text": {"source": "reference_number"},
        "ds_ref2_type": {"value": 2},
        "ds_ref3_type": {"value": 3}
    }
*/


insert into t_fieldmaps(system_default, fieldmap_config) values(true, '
{
    "actual_destination" : {
        "d3canon_name": "actual_destination",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "actual_destination",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "actual_orgin" : {
        "d3canon_name": "actual_orgin",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "actual_orgin",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "appointment_date" : {
        "d3canon_name": "appointment_date",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "pickup_by_date|appointment_date",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": "Legacy abbyy uses pickup_by_date; Wisetrends abbyy uses appointment_by_date"
    },
    "appointment_time" : {
        "d3canon_name": "appointment_time",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "pickup_by_time|appointment_time",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": "Legacy abbyy uses pickup_by_time; Wisetrends abbyy uses appointment_by_time"
    },
    "bill_charge" : {
        "d3canon_name": "bill_charge",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "bill_charge",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "bill_comment" : {
        "d3canon_name": "bill_comment",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "bill_comment",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "bill_to_address" : {
        "d3canon_name": "bill_to_address",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "bill_to_address",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": "Bill To",
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "ds_billto_id",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "booking_number" : {
        "d3canon_name": "bill_to_address",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "booking_number",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": "Bill To",
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Booking",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "carrier" : {
        "d3canon_name": "carrier",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "carrier",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "container_length" : {
        "d3canon_name": "container_length",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "container_length|container_size",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "custom1" : {
        "d3canon_name": "custom1",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": null,
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "custom2" : {
        "d3canon_name": "custom2",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": null,
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "custom3" : {
        "d3canon_name": "custom3",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": null,
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "custom4" : {
        "d3canon_name": "custom4",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": null,
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "custom5" : {
        "d3canon_name": "custom5",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": null,
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "custom6" : {
        "d3canon_name": "custom6",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": null,
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "custom7" : {
        "d3canon_name": "custom7",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": null,
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "custom8" : {
        "d3canon_name": "custom8",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": null,
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "custom9" : {
        "d3canon_name": "custom9",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": null,
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "custom10" : {
        "d3canon_name": "custom10",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": null,
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "customer_number" : {
        "d3canon_name": "customer_number",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "customer_number",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "cutoff_date" : {
        "d3canon_name": "cutoff_date",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "cutoff_date",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "cutoff_time" : {
        "d3canon_name": "cutoff_time",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "cutoff_time",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "division_code" : {
        "d3canon_name": "division_code",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": null,
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": "Division Code",
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "ds_ship_type",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": "Not captured in Abbyy"
    },
    "equipment_provider" : {
        "d3canon_name": "equipment_provider",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "equipment_provider",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "equipment_type" : {
        "d3canon_name": "equipment_type",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "equipment_type",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "event1_location" : {
        "d3canon_name": "event1_location",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "event1_location|location",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.de_site",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "event1_note" : {
        "d3canon_name": "event1_note",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "event1_note",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.de_note",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "event1_type" : {
        "d3canon_name": "event1_type",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "event1_type|type",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.de_type",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": "profittools: H=hook, M=mount, D=deliver, N=dismount, R=drop, P=pickup"
    },
    "event2_location" : {
        "d3canon_name": "event2_location",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "event2_location|location1",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.de_event_site",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "event2_note" : {
        "d3canon_name": "event2_note",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "event2_note",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.de_note",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "event2_type" : {
        "d3canon_name": "event2_type",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "event2_type|type1",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.de_type",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "event3_location" : {
        "d3canon_name": "event3_location",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "event3_location|location2",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.de_event_site",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "event3_note" : {
        "d3canon_name": "event3_note",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "event3_note",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.de_note",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "event3_type" : {
        "d3canon_name": "event3_type",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "event3_type|type2",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.de_type",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "event4_location" : {
        "d3canon_name": "event4_location",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "event4_location|location3",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.de_site",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "event4_note" : {
        "d3canon_name": "event4_note",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "event4_note",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.de_note",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "event4_type" : {
        "d3canon_name": "event4_type",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "event4_type|type3",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.de_type",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "event5_location" : {
        "d3canon_name": "event5_location",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "event5_location|location4",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.de_site",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "event5_note" : {
        "d3canon_name": "event5_note",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "event5_note",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.de_note",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "event5_type" : {
        "d3canon_name": "event5_type",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "event5_type|type4",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.de_type",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "event6_location" : {
        "d3canon_name": "event6_location",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "event6_location|location5",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.de_site",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "event6_note" : {
        "d3canon_name": "event6_note",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "event6_note",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.de_note",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "event6_type" : {
        "d3canon_name": "event6_type",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "event6_type|type5",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.de_event_type",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "event7_location" : {
        "d3canon_name": "event7_location",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "event7_location|location6",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.de_site",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "event7_note" : {
        "d3canon_name": "event7_note",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "event7_note",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.de_note",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "event7_type" : {
        "d3canon_name": "event7_type",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "event7_type|type6",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.de_event_type",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "event8_location" : {
        "d3canon_name": "event8_location",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "event8_location|location7",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.de_site",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "event8_note" : {
        "d3canon_name": "event8_note",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "event8_note",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.de_note",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "event8_type" : {
        "d3canon_name": "event8_type",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "event8_type|type7",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.de_event_type",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "expedite" : {
        "d3canon_name": "expedite",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "expedite",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "fuel_surcharge" : {
        "d3canon_name": "fuel_surcharge",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "fuel_surcharge",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "hazmat" : {
        "d3canon_name": "hazmat",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "hazmat",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "house_bol_hawb" : {
        "d3canon_name": "house_bol_hawb",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "house_bol_hawb",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "contents" : {
        "d3canon_name": "contents",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "contents",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": true,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Items.di_description",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "quantity" : {
        "d3canon_name": "quantity",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "quantity",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Items.di_qty",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "weight" : {
        "d3canon_name": "weight",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "weight",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.di_totitemweight",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "line_haul" : {
        "d3canon_name": "line_haul",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "line_haul",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "load_number" : {
        "d3canon_name": "load_number",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "load_number",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "master_bol_mawb" : {
        "d3canon_name": "master_bol_mawb",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "master_bol_mawb",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "pickup_number" : {
        "d3canon_name": "pickup_number",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "pickup_number",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "port_ramp_of_origin" : {
        "d3canon_name": "port_ramp_of_origin",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "origin_ramp",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": false,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "port_ramp_of_destination" : {
        "d3canon_name": "port_ramp_of_destination",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "destination_ramp",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": false,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "pt_ref1_type" : {
        "d3canon_name": "pt_ref1_type",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": null,
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "ds_ref1_type",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "pt_ref1_text" : {
        "d3canon_name": "pt_ref1_text",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": null,
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "ds_ref1_text",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "pt_ref2_type" : {
        "d3canon_name": "pt_ref2_type",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": null,
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "ds_ref2_type",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "pt_ref2_text" : {
        "d3canon_name": "pt_ref2_text",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": null,
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "ds_ref2_text",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "pt_ref3_type" : {
        "d3canon_name": "pt_ref3_type",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": null,
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "ds_ref3_type",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "pt_ref3_text" : {
        "d3canon_name": "pt_ref3_text",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": null,
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "ds_ref3_text",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "purchase_order_number" : {
        "d3canon_name": "purchase_order_number",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "purchase_order_number",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "rate_box" : {
        "d3canon_name": "rate_box",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "rate_box",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "reference_number" : {
        "d3canon_name": "reference_number",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "reference_number",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "release_number" : {
        "d3canon_name": "release_number",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "release_number",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "seal_number" : {
        "d3canon_name": "seal_number",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "seal_number",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "ship_comment" : {
        "d3canon_name": "ship_comment",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "ship_comment",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "shipment_direction" : {
        "d3canon_name": "shipment_direction",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": null,
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": true,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": "Shipment Direction",
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.movecode",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": "profittools: I/E/O for Import/Export/Oneway(Crosstown)"
    },
    "total_accessorial_charges" : {
        "d3canon_name": "total_accessorial_charges",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "total_accessorial_charges",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "unit_number" : {
        "d3canon_name": "unit_number",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "unit_number",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": "Unit number",
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Equipment.eq_ref",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "vessel" : {
        "d3canon_name": "vessel",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "vessel",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "voyage" : {
        "d3canon_name": "voyage",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "voyage",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": false,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": null,
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": null
    },
    "item_contents" : {
        "d3canon_name": "item_contents",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "contents",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": true,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Items.di_description",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": "This was created by mistake, a duplicate of \'contents\', so delete this entry after 6/1/2021."
    },
    "item_quantity" : {
        "d3canon_name": "item_quantity",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "quantity",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Items.di_qty",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": "This was created by mistake, a duplicate of \'quantity\', so delete this entry after 6/1/2021."
    },
    "item_weight" : {
        "d3canon_name": "item_weight",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": "weight",
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.di_totitemweight",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": "This was created by mistake, a duplicate of \'weight\', so delete this entry after 6/1/2021."
    },
    "event_type" : {
        "d3canon_name": "event_type",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": null,
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.de_event_type",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": "This was created by mistake, a duplicate of \'event1_type\', so delete this entry after 6/1/2021."
    },
    "event_note" : {
        "d3canon_name": "event_note",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": null,
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.de_note",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": "This was created by mistake, a duplicate of \'event1_note\', so delete this entry after 6/1/2021."
    },
    "event_address_tms_code" : {
        "d3canon_name": "event_address_tms_code",
        "d3canon_table": null,
        "d3canon_column": null,
        "abbyy_source_field": null,
        "abbyy_source_regex": null,
        "available": true,
        "templateable": true,
        "use_template_value": true,
        "adminreview_if_missing": false,
        "adminreview_validation_regex": null,
        "screen_hide": false,
        "screen_name": null,
        "constant_value": null,
        "post_process_source_field": null,
        "post_process_source_regex": null,
        "profittools_destination": "Events.de_site",
        "cargowise_destination": null,
        "compcare_destination": null,
        "notes": "This was created by mistake, a duplicate of \'event1_location\', so delete this entry after 6/1/2021."
    }
}
');




-- TCompaniesDemo site, just testing...
insert into t_fieldmaps(fieldmap_config) values('
{
    "contents" : {
        "use_template_value": false
    },
    "weight" : {
        "use_template_value": false
    },
    "quantity" : {
        "use_template_value": false
    },
    "event1_type" : {
        "use_template_value": false
    },
    "event1_note" : {
        "use_template_value": false
    },
    "event1_location" : {
        "use_template_value": false
    }
}');
set @TCOMPANIESDEMO_COMPANY_FIELDMAP_ID = (SELECT LAST_INSERT_ID());
set @TCOMPANIESDEMO_COMPANY_ID = (select id from t_companies where name = 'TCompaniesDemo');
update t_companies set t_fieldmap_id=@TCOMPANIESDEMO_COMPANY_FIELDMAP_ID where id=@TCOMPANIESDEMO_COMPANY_ID;




-- For Zariz, they don't want decription/weight/quantity to be templated
insert into t_fieldmaps(fieldmap_config) values('
{
    "contents" : {
        "use_template_value": false
    },
    "weight" : {
        "use_template_value": false
    },
    "quantity" : {
        "use_template_value": false
    }
}
');
set @ZARIZ_COMPANY_FIELDMAP_ID = (SELECT LAST_INSERT_ID());
set @ZARIZ_COMPANY_ID = (select id from t_companies where name = 'Zariz');
update t_companies set t_fieldmap_id=@ZARIZ_COMPANY_FIELDMAP_ID where id=@ZARIZ_COMPANY_ID;




-- for TransportDSquare, they don't want events to be templated
insert into t_fieldmaps(fieldmap_config) values('
{
    "event1_type" : {
        "use_template_value": false
    },
    "event1_note" : {
        "use_template_value": false
    },
    "event1_location" : {
        "use_template_value": false
    }
}
');
set @TRANSPORTDSQUARE_COMPANY_FIELDMAP_ID = (SELECT LAST_INSERT_ID());
set @TRANSPORTDSQUARE_COMPANY_ID = (select id from t_companies where name = 'TransportDSquare');
update t_companies set t_fieldmap_id=@TRANSPORTDSQUARE_COMPANY_FIELDMAP_ID where id=@TRANSPORTDSQUARE_COMPANY_ID;
