name: cypress-frontend

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          start: npm run serve & wait-on http://localhost:8080
          working-directory: frontend