name: tests

on: [push, pull_request]

jobs:
  cypress-run:
    name: Frontend Tests

    runs-on: ubuntu-16.04

    steps:
    
    - name: Setup npm package
      run: npm init -y && npm install

    - name: Cypress.io
      uses: cypress-io/github-action@v1.16.1

    - name: Checkout
      uses: actions/checkout@v1

    # Install NPM dependencies, cache them correctly
    # and run all Cypress tests
    - name: Cypress run
      uses: cypress-io/github-action@v2

  tests:
    name: Laravel Tests

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: omdb_test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-7.4-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, bcmath, mysql, imagick
          coverage: none

      - name: Install dependencies
        run: |
          composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_PASSWORD }}"
          composer install --no-interaction --no-progress

      - name: Migrate database
        run: php artisan migrate:fresh
        env:
          APP_KEY: base64:51OJ4K5Yy7Q8rYjoL9PpJXPN0HkIiKc9trE584Wh4LQ=
          APP_ENV: testing
          SANCTUM_STATEFUL_DOMAINS: 127.0.0.8,localhost,127.0.0.1
          DB_HOST: 127.0.0.1
          DB_CONNECTION: testing
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_USERNAME: root
          DB_DATABASE: omdb
          AWS_REGION: us-east-2
          AWS_DEFAULT_REGION: us-east-2

      - name: Execute tests
        run: vendor/bin/phpunit --verbose
        env:
          APP_KEY: base64:51OJ4K5Yy7Q8rYjoL9PpJXPN0HkIiKc9trE584Wh4LQ=
          SANCTUM_STATEFUL_DOMAINS: 127.0.0.8,localhost,127.0.0.1
          DB_HOST: 127.0.0.1
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_USERNAME: root
          DB_DATABASE: omdb
          AWS_REGION: us-east-2
          AWS_DEFAULT_REGION: us-east-2